"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# No hardcoded fallback — a committed key (even one labeled "dev-only") is
# still a secret checked into source control. Generate one with:
#   python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"
# and put it in .env (gitignored) as DJANGO_SECRET_KEY=...
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    from django.core.exceptions import ImproperlyConfigured

    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY is not set. Add it to your .env file."
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "true").lower() == "true"

# Comma-separated in .env, e.g. ALLOWED_HOSTS=api.example.com,example.com
ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get("ALLOWED_HOSTS", "*").split(",") if h.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # EmbedIQ apps
    "apps.retrieval.apps.RetrievalConfig",
    "apps.generation",
    "apps.conversations",
    "apps.accounts",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "config.middleware.RequestTraceMiddleware",
    "config.middleware.RequestTimingMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database — Postgres via DATABASE_URL in .env
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        env="DATABASE_URL",
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# --- EmbedIQ shared config ---
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")
QDRANT_URL = os.environ.get("QDRANT_URL", "http://localhost:6333")
COLLECTION_NAME = os.environ.get("COLLECTION_NAME", "my_docs")
EMBED_DIM = int(os.environ.get("EMBED_DIM", 3072))
TOP_K = int(os.environ.get("TOP_K", 5))
GEN_MODEL = os.environ.get("GEN_MODEL", "gemini-3.5-flash-lite")
# Fast/cheap model used for query rewriting, HyDE, and CRAG grading/rewriting —
# distinct from GEN_MODEL, which produces the user-facing answer.
UTILITY_MODEL = os.environ.get("UTILITY_MODEL", "gemini-3.5-flash-lite")
MAX_HISTORY_TURNS = int(os.environ.get("MAX_HISTORY_TURNS", 10))

# --- Gemini request timeouts (milliseconds) ---
# Without these a hung call has no ceiling: tenacity retries it up to 3 times
# with exponential backoff, so one slow response becomes a ~30s request.
# Utility calls (rewrite / HyDE / CRAG grading) sit in front of retrieval and
# every caller of them fails open, so they get the tightest budget.
# The Gemini API rejects any http_options.timeout below 10000ms outright
# ("Manually set deadline Ns is too short. Minimum allowed deadline is 10s."),
# so these floors are a hard API requirement, not just a latency preference.
GEMINI_UTILITY_TIMEOUT_MS = int(os.environ.get("GEMINI_UTILITY_TIMEOUT_MS", 10000))
GEMINI_EMBED_TIMEOUT_MS = int(os.environ.get("GEMINI_EMBED_TIMEOUT_MS", 10000))
GEMINI_GENERATE_TIMEOUT_MS = int(os.environ.get("GEMINI_GENERATE_TIMEOUT_MS", 15000))

# Retry budget. Utility calls are best-effort — one quick retry, then fail open
# to the un-rewritten query, rather than making the user wait out a backoff.
# The user-facing generation call keeps a fuller budget.
GEMINI_UTILITY_MAX_ATTEMPTS = int(os.environ.get("GEMINI_UTILITY_MAX_ATTEMPTS", 2))
GEMINI_UTILITY_RETRY_MAX_WAIT = float(os.environ.get("GEMINI_UTILITY_RETRY_MAX_WAIT", 2))
GEMINI_GENERATE_MAX_ATTEMPTS = int(os.environ.get("GEMINI_GENERATE_MAX_ATTEMPTS", 3))
GEMINI_GENERATE_RETRY_MAX_WAIT = float(
    os.environ.get("GEMINI_GENERATE_RETRY_MAX_WAIT", 5)
)

# --- Chunking config ---
# Character-based sizes. Approx token equivalents (English):
#   PARENT: 2500 chars ≈ 500–800 tokens (LLM context window)
#   CHILD:  600 chars  ≈ 100–200 tokens (embedding granularity)
# Children use ~10% overlap automatically (see ingest_service._chunk_text).
PARENT_CHUNK_SIZE = int(os.environ.get("PARENT_CHUNK_SIZE", 2500))
CHILD_CHUNK_SIZE = int(os.environ.get("CHILD_CHUNK_SIZE", 600))

# --- Reranker config ---
RERANKER_ENABLED = os.environ.get("RERANKER_ENABLED", "true").lower() == "true"
RERANKER_MODEL = os.environ.get("RERANKER_MODEL", "BAAI/bge-reranker-base")
RERANK_CANDIDATE_LIMIT = int(os.environ.get("RERANK_CANDIDATE_LIMIT", 25))

# --- HyDE config ---
USE_HYDE = os.environ.get("USE_HYDE", "false").lower() == "true"
HYDE_MODE = os.environ.get("HYDE_MODE", "replace")
HYDE_MAX_OUTPUT_TOKENS = int(os.environ.get("HYDE_MAX_OUTPUT_TOKENS", 200))

# Thinking budget for the pre-retrieval utility calls (rewrite / HyDE / CRAG
# grading). These are mechanical text transforms, so thinking tokens are pure
# added latency in front of retrieval. 0 disables thinking; -1 leaves the
# model's own default in place.
UTILITY_THINKING_BUDGET = int(os.environ.get("UTILITY_THINKING_BUDGET", 0))

_VALID_HYDE_MODES = {"replace", "ensemble"}
if HYDE_MODE not in _VALID_HYDE_MODES:
    from django.core.exceptions import ImproperlyConfigured

    raise ImproperlyConfigured(
        f"HYDE_MODE must be one of {_VALID_HYDE_MODES}, got {HYDE_MODE!r}"
    )

# --- CRAG config ---
CRAG_ENABLED = os.environ.get("CRAG_ENABLED", "false").lower() == "true"
CRAG_CONFIDENCE_THRESHOLD = float(os.environ.get("CRAG_CONFIDENCE_THRESHOLD", "0.6"))
CRAG_MIN_RELEVANT_CHUNKS = int(os.environ.get("CRAG_MIN_RELEVANT_CHUNKS", "2"))

# --- LangSmith tracing (token/latency monitoring) ---
# Read directly by the langsmith SDK (not through Django settings):
# LANGSMITH_TRACING, LANGSMITH_API_KEY, LANGSMITH_PROJECT. See .env.
# @traceable/trace() calls throughout apps/retrieval and apps/generation
# no-op automatically when LANGSMITH_TRACING is unset/false.

# --- Table ingestion config ---
# Max data rows per table chunk. The header row is repeated in every batch.
# Prevents a single large table from exceeding the LLM context window.
TABLE_ROW_BATCH_SIZE = int(os.environ.get("TABLE_ROW_BATCH_SIZE", 20))

# --- Upload / ingestion limits ---
ALLOWED_UPLOAD_EXTENSIONS = set(
    e.strip().lower()
    for e in os.environ.get("ALLOWED_UPLOAD_EXTENSIONS", ".txt,.pdf,.md").split(",")
    if e.strip()
)
MAX_UPLOAD_SIZE_BYTES = int(
    os.environ.get("MAX_UPLOAD_SIZE_MB", 50)
) * 1024 * 1024
QDRANT_UPSERT_BATCH_SIZE = int(os.environ.get("QDRANT_UPSERT_BATCH_SIZE", 200))

# --- CRAG grading concurrency ---
# Max concurrent grading threads per corrective_retrieve() call.
CRAG_MAX_GRADE_WORKERS = int(os.environ.get("CRAG_MAX_GRADE_WORKERS", 4))

# --- Authentication & JWT ---
from datetime import timedelta  # noqa: E402

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "UPDATE_LAST_LOGIN": True,
}

# Google OAuth2 client ID — set this in .env
GOOGLE_CLIENT_ID = os.environ.get("GOOGLE_CLIENT_ID", "")

# --- Timing instrumentation ---
# Turns off every stage()/request timing log without touching call sites.
TIMING_ENABLED = os.environ.get("TIMING_ENABLED", "true").lower() == "true"
# Requests slower than this are logged at WARNING instead of INFO.
SLOW_REQUEST_MS = int(os.environ.get("SLOW_REQUEST_MS", 3000))
# Path prefixes excluded from request timing — health checks would flood the log.
TIMING_SKIP_PATHS = tuple(
    p.strip()
    for p in os.environ.get("TIMING_SKIP_PATHS", "/health/").split(",")
    if p.strip()
)

# --- Logging config ---
os.makedirs(BASE_DIR / "logs", exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "trace_id": {
            "()": "config.middleware.TraceIdFilter",
        },
    },
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} [{name}:{lineno}] [trace:{trace_id}] {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
            "filters": ["trace_id"],
        },
        "file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs" / "embediq.log",
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
            "backupCount": 5,
            "formatter": "verbose",
            "filters": ["trace_id"],
        },
        # Timing events also get their own file so they can be grepped/parsed
        # without the surrounding application log noise.
        "timing_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs" / "timing.log",
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
            "backupCount": 5,
            "formatter": "verbose",
            "filters": ["trace_id"],
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        # propagate=False so timing lines aren't emitted twice via root.
        "embediq.timing": {
            "handlers": ["console", "file", "timing_file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
