# Generated by Django 6.0.6 on 2026-07-12 13:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retrieval", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("page_number", models.IntegerField()),
                ("image", models.ImageField(upload_to="document_images/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="retrieval.document",
                    ),
                ),
            ],
        ),
    ]
